CREATE TABLE attachments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    blob      OID,
    ticket_id BIGINT,
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);