ALTER SEQUENCE users_id_seq RESTART WITH 1000;
ALTER SEQUENCE tickets_id_seq RESTART WITH 1000;
ALTER SEQUENCE attachments_id_seq RESTART WITH 1000;
ALTER SEQUENCE comments_id_seq RESTART WITH 1000;
ALTER SEQUENCE records_id_seq RESTART WITH 1000;


